// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* generated by NAPI-RS; libc detection hardened by scripts/harden-native-loader.mjs */

// This prefix replaces napi-rs's generated libc probe. Keep it CommonJS because
// it is copied verbatim into native/index.js, which is itself CommonJS.
const { closeSync, openSync, readSync, readdirSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isFileMusl = (file) => file.includes('libc.musl-') || file.includes('ld-musl-')

const isMuslFromReport = () => {
  try {
    if (!process.report || typeof process.report.getReport !== 'function') {
      return null
    }
    const report = process.report.getReport()
    if (report && report.header && report.header.glibcVersionRuntime) {
      return false
    }
    if (report && Array.isArray(report.sharedObjects) && report.sharedObjects.some(isFileMusl)) {
      return true
    }
  } catch {
    // Continue with filesystem and ELF inspection.
  }
  return null
}

const isMuslFromFilesystem = () => {
  for (const directory of ['/lib', '/usr/lib']) {
    try {
      if (readdirSync(directory).some(isFileMusl)) {
        return true
      }
    } catch {
      // A missing or unreadable conventional library directory is inconclusive.
    }
  }
  return null
}

const readUInt = (buffer, offset, bytes, littleEndian) => {
  if (offset < 0 || offset + bytes > buffer.length) {
    return null
  }
  if (bytes === 2) {
    return littleEndian ? buffer.readUInt16LE(offset) : buffer.readUInt16BE(offset)
  }
  if (bytes === 4) {
    return littleEndian ? buffer.readUInt32LE(offset) : buffer.readUInt32BE(offset)
  }
  if (bytes === 8) {
    const value = littleEndian ? buffer.readBigUInt64LE(offset) : buffer.readBigUInt64BE(offset)
    return value <= BigInt(Number.MAX_SAFE_INTEGER) ? Number(value) : null
  }
  return null
}

const isMuslFromElfInterpreter = () => {
  let fd
  try {
    fd = openSync(process.execPath, 'r')
    const header = Buffer.alloc(64)
    if (readSync(fd, header, 0, header.length, 0) < 52) {
      return null
    }
    if (header[0] !== 0x7f || header[1] !== 0x45 || header[2] !== 0x4c || header[3] !== 0x46) {
      return null
    }

    const elfClass = header[4]
    const dataEncoding = header[5]
    if ((elfClass !== 1 && elfClass !== 2) || (dataEncoding !== 1 && dataEncoding !== 2)) {
      return null
    }
    const littleEndian = dataEncoding === 1
    const is64Bit = elfClass === 2
    const programHeaderOffset = readUInt(header, is64Bit ? 32 : 28, is64Bit ? 8 : 4, littleEndian)
    const programHeaderSize = readUInt(header, is64Bit ? 54 : 42, 2, littleEndian)
    const programHeaderCount = readUInt(header, is64Bit ? 56 : 44, 2, littleEndian)
    if (
      programHeaderOffset === null ||
      programHeaderSize === null ||
      programHeaderCount === null ||
      programHeaderSize < (is64Bit ? 56 : 32) ||
      programHeaderCount > 1024
    ) {
      return null
    }

    const programHeader = Buffer.alloc(programHeaderSize)
    for (let index = 0; index < programHeaderCount; index += 1) {
      const offset = programHeaderOffset + index * programHeaderSize
      if (readSync(fd, programHeader, 0, programHeader.length, offset) !== programHeader.length) {
        return null
      }
      const type = readUInt(programHeader, 0, 4, littleEndian)
      if (type !== 3) continue // PT_INTERP

      const interpreterOffset = readUInt(programHeader, is64Bit ? 8 : 4, is64Bit ? 8 : 4, littleEndian)
      const interpreterSize = readUInt(programHeader, is64Bit ? 32 : 16, is64Bit ? 8 : 4, littleEndian)
      if (
        interpreterOffset === null ||
        interpreterSize === null ||
        interpreterSize < 1 ||
        interpreterSize > 4096
      ) {
        return null
      }
      const interpreter = Buffer.alloc(interpreterSize)
      if (readSync(fd, interpreter, 0, interpreter.length, interpreterOffset) !== interpreter.length) {
        return null
      }
      return isFileMusl(interpreter.toString('utf8'))
    }
  } catch {
    return null
  } finally {
    if (fd !== undefined) {
      try {
        closeSync(fd)
      } catch {
        // The loader must not turn a failed best-effort close into an import failure.
      }
    }
  }
  return null
}

const isMusl = () => {
  if (process.platform !== 'linux') {
    return false
  }
  for (const detector of [isMuslFromReport, isMuslFromFilesystem, isMuslFromElfInterpreter]) {
    const result = detector()
    if (result !== null) {
      return result
    }
  }
  // Unknown Linux libc: try the glibc package and let its require fail normally.
  return false
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./fs-safe-native.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-android-arm64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./fs-safe-native.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-android-arm-eabi')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./fs-safe-native.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-win32-x64-gnu')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./fs-safe-native.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-win32-x64-msvc')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./fs-safe-native.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-win32-ia32-msvc')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./fs-safe-native.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-win32-arm64-msvc')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./fs-safe-native.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@openclaw/fs-safe-native-darwin-universal')
      const bindingPackageVersion = require('@openclaw/fs-safe-native-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./fs-safe-native.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-darwin-x64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./fs-safe-native.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-darwin-arm64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./fs-safe-native.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-freebsd-x64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./fs-safe-native.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-freebsd-arm64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./fs-safe-native.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-x64-musl')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./fs-safe-native.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-x64-gnu')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./fs-safe-native.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-arm64-musl')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./fs-safe-native.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-arm64-gnu')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./fs-safe-native.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-arm-musleabihf')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./fs-safe-native.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./fs-safe-native.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-loong64-musl')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./fs-safe-native.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-loong64-gnu')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./fs-safe-native.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-riscv64-musl')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./fs-safe-native.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@openclaw/fs-safe-native-linux-riscv64-gnu')
          const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./fs-safe-native.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-linux-ppc64-gnu')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./fs-safe-native.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-linux-s390x-gnu')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./fs-safe-native.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-openharmony-arm64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./fs-safe-native.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-openharmony-x64')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./fs-safe-native.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@openclaw/fs-safe-native-openharmony-arm')
        const bindingPackageVersion = require('@openclaw/fs-safe-native-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.5.0-dev.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.5.0-dev.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./fs-safe-native.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('@openclaw/fs-safe-native-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.fstatIdentity = nativeBinding.fstatIdentity
module.exports.linkBeneath = nativeBinding.linkBeneath
module.exports.mkdirBeneath = nativeBinding.mkdirBeneath
module.exports.openBeneath = nativeBinding.openBeneath
module.exports.renameNoReplace = nativeBinding.renameNoReplace
