/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface FileIdentity {
  dev: number
  ino: number
  mode: number
  nlink: number
  size: number
  isFile: boolean
  isDirectory: boolean
  isSymbolicLink: boolean
}

export declare function fstatIdentity(fd: number): FileIdentity

export declare function linkBeneath(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void

export declare function mkdirBeneath(rootFd: number, relPath: string, mode: number): void

export declare function openBeneath(rootFd: number, relPath: string, flags: number): number

export declare function renameNoReplace(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void
