/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractArchiveNative(path: string, kind: string, rootFd: number, plan: Array<NativeArchivePlanEntry>, maxMetaEntryBytes: number, signal: AbortSignal): Promise<void>

export interface FileIdentity {
  dev: number
  ino: number
  mode: number
  nlink: number
  size: number
  isFile: boolean
  isDirectory: boolean
  isSymbolicLink: boolean
}

export declare function fstatIdentity(fd: number): FileIdentity

export declare function inspectArchiveNative(path: string, kind: string, maxEntries: number, maxMetaEntryBytes: number, maxManifestBytes: number, signal: AbortSignal): Promise<Array<NativeArchiveEntry>>

export declare function linkBeneath(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void

export declare function mkdirBeneath(rootFd: number, relPath: string, mode: number): void

export interface NativeArchiveEntry {
  index: number
  path: string
  kind: string
  size: number
  mode: number
}

export interface NativeArchivePlanEntry {
  index: number
  path: string
  kind: string
  size: number
  mode: number
}

export declare function openBeneath(rootFd: number, relPath: string, flags: number): number

export declare function readArchiveEntryNative(path: string, kind: string, requested: string, maxBytes: number, maxEntries: number, maxMetaEntryBytes: number, signal: AbortSignal): Promise<Buffer>

export declare function renameNoReplace(sourceRootFd: number, sourceRelPath: string, targetRootFd: number, targetRelPath: string): void
