export {
  FsSafeError,
  categorizeFsSafeError,
  type FsSafeErrorCategory,
  type FsSafeErrorCode,
} from "./errors.js";
export {
  DEFAULT_ROOT_MAX_BYTES,
  root,
  type HardlinkPolicy,
  type OpenResult,
  type ReadResult,
  type Root,
  type RootAppendOptions,
  type RootCopyOptions,
  type RootCreateJsonOptions,
  type RootCreateOptions,
  type RootDefaults,
  type RootOpenOptions,
  type RootOpenWritableOptions,
  type RootOptions,
  type RootReadOptions,
  type RootWriteJsonOptions,
  type RootWriteOptions,
  type SymlinkPolicy,
  type WritableOpenMode,
  type WritableOpenResult,
} from "./root.js";
